name : 'Bump version'
description: 'JS action for autoupdate version based on the commit message'
inputs:
  major-flags-words:  # id of input
    description: 'Words that suggest update is Major'
    required: false
    default: 'MAJOR, BIG'
  minor-flags-words:  # id of input
    description: 'Words that suggest update is Minor'
    required: false
    default: 'MINOR'
  patch-flags-words:  # id of input
    description: 'Words that suggest update is Patch'
    required: false
    default: 'PATCH'
outputs:
  output-version: # id of output
    description: 'Output version'
runs:
  using: 'node12'
  main: 'dist/index.js'
