on: [push]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    name: A job to bump version based on commit message
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Input 
        id: input
        uses: ./
        with:
          input-version: '3.0.0'
      - name: Get the output time
        run: echo "The time was ${{ steps.input.outputs.output-version }}"
